apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  volumes:
  - name: nfs-volume
    persistentVolumeClaim:
      claimName: pvc-nfs
  containers:
  - image: busybox
    name: busybox    
    stdin: true
    tty: true
    volumeMounts:
    - name: nfs-volume
      mountPath: /storage/nfs/L/kube
