kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: containercap-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 250Mi
  storageClassName: containercap-storage
