apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
  labels:
    type: local
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "172.18.104.110"
    path: "/storage/nfs"