apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
  labels:
    type: local
spec:
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
  nfs:
    #server: "10.10.131.44"
    #path: "/mnt/ContainerCap/"
    server: "10.2.0.75"
    path: "/groups/ilabt-imec-be/containercap/ContainerCap/nfs/"

